### PR TITLE
Copy site from hanamirb.org

### PR DESCRIPTION
**Pull request by davydovanton**
I think we need to create a simple version of the site that's why I created this PR.
It's just copied from http://hanamirb.org without unnecessary information (I dropped guides, blogs, etc).

/cc @hanami/ecosystem

### CODE REVIEW

**Comment by jodosha** [comment]
@davydovanton Can you please remove the logos from other companies? Thanks.

**Comment by davydovanton** [comment]
@jodosha done 👍

**Comment by cllns** [comment]
Should this be merged into a new `build` branch, instead of `master`?

Also, I'm suspicious of having two copies of the site around. Seems like it'll be annoying to maintain. Instead, could we keep just the website repo, and modify that build process to clone this repo and build ecosystem pages from it? Might be overkill at this stage, but I think that might be a better solution long-term.

**Comment by pascalbetz** [comment]
Not sure I understand....
@davydovanton this should be the "home" for all the ecosystem pages? Shouldn't we integrate those into the main site?

**Comment by jodosha** [comment]
@davydovanton I understood the idea of having a separate website since the first moment. But @pascalbetz question can be a good chance to openly explain the reasons why we need it, by including pros/cons of the decision.

Please note that I'm not expressing my opinion, just guiding the discussion to be more open and to remember in 6 months why we did it.

**Comment by AlfonsoUceda** [comment]
@davydovanton could you explain this? I don't understand the reason but as @jodosha said, it would be good for the discussion.

**Pull request closed without merging**
