### PR TITLE
Add list of guides to write

### LINKED ISSUE #1: List of all unnecessary guides
I think we need to create the general issue with all parts which we want to cover.

## What guides we need to create
* omniauth _(I have working code for this)_
* auth
* slug
* test DB cleaner
* webpack (react or vue) _(I have working code for this)_
* testing (rspec-hanami, vcr, etc) _(I have working code for this)_
* service object _(I have working code for this)_
* presenters
* sidekiq, resque
* file uploading
* Other DB (monga, couchbase, etc)
* pagination
* email preview _(I have blog post for this)_
* API documentation
* logging
* server monitoring
* deploy
* state machine
* A/B testing (?)
* i18n
* web sockets
* JSON response

So, let's try to discuss this 😊 

/cc @hanami/ecosystem

### PR DESCRIPTION
**Pull request by cllns**
Let's put this list of what we want to write in the README, so we have some source control on it :)

Also happy to make it `TODO.md`, or use the Wiki.

I pulled the content from #1 and re-organized it a bit, and added some stuff. Also turned it into check lists :)

Please give me your thoughts on stuff that needs to be added, removed or modified/clarified.

(Closes #1)

### CODE REVIEW

**Comment by davydovanton** [comment]
looks good for me

**Comment by cllns** [comment]
Just updated this.

I'm not sure adding this to the README is the best idea. I have started assigning people who volunteered to write certain ones, with just writing their GitHub handle next to them, but there's no way to track that.

What do you think about experimenting with GitHub's new 'Project' feature? https://help.github.com/articles/adding-issues-and-pull-requests-to-a-project/
Seems like this could be a good use for it.

We can create cards (which are *not* Issues) for each of these and put them in the Backlog. Then as we want to pull them up (or people volunteer), we can promote the cards to being Issues, which will get worked on. Thoughts? @hanami/ecosystem

**Comment by davydovanton** [comment]
@cllns cool idea. we can add this list to GitHub wiki and after that create an issue for each part and add this issues to github project. What do you think?

**Comment by cllns** [comment]
I like the idea of moving this list to the wiki!

But then we'd create project Cards directly from that that wiki list, which are **not** Issues yet. Instead, they can be made into Issues when they're needed. I think this will help us focus and prioritize guides, rather than getting overwhelmed. That cool with you?

Otherwise, we could just use wiki + Issues and do our own project management.

**Comment by davydovanton** [comment]
yep, wiki + project looks good for me 👍

**Comment by cllns** [comment]
Closing in favor of https://github.com/hanami/ecosystem/wiki/Integrations (which I copied from the current state of this PR)

we'll make a project from the list there.

**Pull request closed without merging**
